version: '3.8'

services:
  db:
    image: postgres:13
    container_name: transaction_db
    environment:
      POSTGRES_DB: transaction_management
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    ports:
      - "5442:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: transaction_app
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/transaction_management
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: password
    ports:
      - "8080:8080"

volumes:
  postgres_data: